### ISSUE TITLE
normalization

### ISSUE THREAD

**Issue by v-mahughes** [czbiohub-sf/tabula-sapiens#41]
What normalization + transformation has been applied to transform the Tabula Sapiens anndata.raw.X object to the anndata.X object?

**Comment by smzt** [comment]
Hi,
I'm also wondering the same. 
Is there any document where we can find the whole pipeline that was applied to create Tabula Sapiens? Reference and annotations, normalization method, number of variable features, number of dimensions, etc? 
Thanks in advance.

Best regards,

Sheila

**Comment by wujialu** [comment]
same questions

**Comment by aopisco** [comment]
that information is available in the methods with the publication, and in short from the [data portal](https://tabula-sapiens.sf.czbiohub.org/organs)
